"""initial migration

Revision ID: 3c0b6cfb228f
Revises: 
Create Date: 2023-03-07 18:08:23.576841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3c0b6cfb228f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("groups")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("display_name", sa.String(length=200), nullable=True)
        )
        batch_op.add_column(sa.Column("username", sa.String(length=200), nullable=True))
        batch_op.add_column(
            sa.Column("profile_picture_url", sa.String(length=200), nullable=True)
        )
        batch_op.alter_column(
            "phone",
            existing_type=sa.VARCHAR(length=12),
            type_=sa.String(length=200),
            existing_nullable=True,
        )
        batch_op.drop_column("group_id")
        batch_op.drop_column("email")
        batch_op.drop_column("name")
        batch_op.drop_column("password")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "password", sa.VARCHAR(length=200), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "name", sa.VARCHAR(length=200), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "email", sa.VARCHAR(length=200), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("group_id", postgresql.UUID(), autoincrement=False, nullable=True)
        )
        batch_op.alter_column(
            "phone",
            existing_type=sa.String(length=200),
            type_=sa.VARCHAR(length=12),
            existing_nullable=True,
        )
        batch_op.drop_column("profile_picture_url")
        batch_op.drop_column("username")
        batch_op.drop_column("display_name")

    op.create_table(
        "groups",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="groups_pkey"),
    )
    # ### end Alembic commands ###
