name: Development

on:
  push:
    paths:
      - "**.py"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: psf/black@stable
      - uses: pre-commit/action@v3.0.0

